name = "roll-dorado-casino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-casino.com.pt"
HMAC_KEY = "7cc16d4fcc483349cfb013242d58a9340a10cb073fe6a8bdcf3f1ec22a0e7f73"
COOKIE_NAME = "kmg"
PLAY_PATH = "play"
BUTTON_ID = "p53a4489a3ea710da5946d6167b59a6a2"
GATE_SALT = "4ae3e617cc173262"
